apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  secretName: secret-tls
  renewBefore: 240h
  duration: 2160h
  commonName: hack-godtfredsen.no
  dnsNames:
  - hack-godtfredsen.no
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
