apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploymenttest
  template:
    metadata:
      labels:
        app: deploymenttest
    spec:
      containers:
      - name: deploymenttest
        image: ghcr.io/stianhg/deploymenttest # {"$imagepolicy": "flux-system:deploymenttest-policy"}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_KEYCLOAK_URL
          valueFrom:
            secretKeyRef: 
              name: react-app-secrets
              key: REACT_APP_KEYCLOAK_URL         
          
        - name: REACT_APP_KEYCLOAK_REALM
          valueFrom:
            secretKeyRef: 
              name: react-app-secrets
              key: REACT_APP_KEYCLOAK_REALM
              
        - name: REACT_APP_KEYCLOAK_CLIENTID
          value: "React"
