apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_test
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deployment_test
  template:
    metadata:
      annotations:        
      labels:
        app: deployment_test
    spec:
      containers:
      - name: poddeployment_test
        image: ghcr.io/stianHG/deployment_test:6.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP        
        command:
        - ./podinfo
        - --port=9898        
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: UI_COLOR
          value: "#34577c"
        livenessProbe:
          exec:
            command:
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - http
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
