apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploymenttest
  template:
    metadata:
      labels:
        app: deploymenttest
    spec:
      containers:
      - name: deploymenttest
        image: ghcr.io/stianhg/deploymenttest:sha-0cfb2c7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ENV_TEST
          value: "testValue"
