apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: general
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx-class-name
    cert-manager.io/cluster-issuer: cluster-issuer-name
    nginx.ingress.kubernetes.io/ssl-redirect: true
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hack-godtfredsen.no
    secretName: secret-tls
  rules:  
  - host: auth.hack-godtfredsen.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
              
  - host: hack-godtfredsen.no
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080

  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
