apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: hbr-keycloak
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: keycloak-db
