apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: powermeter
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: keycloak-db
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: hbr-keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
