apiVersion: v1
kind: Service
metadata:
  name: deploymenttest
spec:
  type: ClusterIP
  selector:
    app: deploymenttest
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http   
