apiVersion: v1
kind: Service
metadata:
  name: deployment_test
spec:
  type: ClusterIP
  selector:
    app: deployment_test
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http   
