apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployment_test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dployment_test
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # scale up if usage is above
        # 99% of the requested CPU (100m)
        averageUtilization: 99
