name: Docker Image CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      pushImage:
        description: Publish image to repository
        type: boolean
        required: true
        default: true

jobs:

  test_and_publih:
    name: Test and publish image

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Set build version
        uses: dotnet/nbgv@master
        id: nbgv
        with:
          setCommonVars: true

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: stianhg/deployment_test

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: .github/pack-published.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
