name: Docker Image CI
permissions:
  contents: write
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      pushImage:
        description: Publish image to repository
        type: boolean
        required: true
        default: true

env:
  REGISTRY: ghcr.io
  DOCKERHUB_USERNAME: stianhg
  
jobs:         
  build_publish:
    name: Build and publish image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username:  ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
                  
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: .github/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ GITHUB_SHA::7 }}
          labels: ${{ steps.meta.outputs.labels }}


